#include "environment.hpp"
#include "../program_entry/program_entry.hpp"
#include "../gameplay/player_state.hpp"
namespace th20::source::overlay {
namespace ps=gameplay::player_state;
WeaponStoneInf::WeaponStoneInf():age{},animation_handle(0),file(nullptr),main_weapon(nullptr),focused_weapon(nullptr),unfocused_weapon(nullptr),passive_weapon(nullptr),counter{},mesh(nullptr),mesh_age{},phase(0),position{},cancellation_age{},cancellation_radius(0),main_shooting(0),view_index(0),context(nullptr){}
WeaponStoneInf::~WeaponStoneInf(){auto& host=environment();for(Weapon** slot:{&main_weapon,&focused_weapon,&unfocused_weapon,&passive_weapon}){host.destroy_weapon(*slot);*slot=nullptr;}host.destroy_mesh(mesh);mesh=nullptr;scheduler::remove(*program_entry::function_controller,program_entry::scheduler_environment,update_node);scheduler::remove(*program_entry::function_controller,program_entry::scheduler_environment,draw_node);host.unload_animation(23);}
void WeaponStoneInf::enable_callbacks(){runtime::CallbackOwner::enable_callbacks();auto& host=environment();auto& player=*game_session::context(0).current_player;refresh_selection(*this,ps::read<int>(player,8),host);if(host.restarting())for(int slot=0;slot<4;++slot)player.bytes_2c[slot==1?2:slot==2?1:slot==3?3:0]=host.replay_inherited(slot);reset(*controller(),host.stage_id());}
void WeaponStoneInf::disable_callbacks(){runtime::CallbackOwner::disable_callbacks();}
void WeaponStoneInf::select_context(int index) noexcept{view_index=index;context=&game_session::context(index);}
WeaponStoneInf* controller(int index) noexcept{return static_cast<WeaponStoneInf*>(game_session::context(index).overlay_owner);}
void select_main(WeaponStoneInf& owner,int character,int stone,Environment& host){host.destroy_weapon(owner.main_weapon);owner.main_weapon=nullptr;ps::write(*game_session::context(0).current_player,0xc,stone);owner.main_weapon=host.create_weapon(character,stone);owner.main_weapon->role=0;owner.main_weapon->stone_id=stone;}
void select_focused(WeaponStoneInf& owner,int character,int stone,Environment& host){host.destroy_weapon(owner.focused_weapon);owner.focused_weapon=nullptr;auto& p=*game_session::context(0).current_player;p.bytes_2c[1]=0;if(stone==8){stone=ps::read<int>(p,0x1c);p.bytes_2c[1]=1;}ps::write(p,0x10,stone);owner.focused_weapon=host.create_weapon(character,stone);owner.focused_weapon->role=2;owner.focused_weapon->stone_id=stone;}
void select_unfocused(WeaponStoneInf& owner,int character,int stone,Environment& host){host.destroy_weapon(owner.unfocused_weapon);owner.unfocused_weapon=nullptr;auto& p=*game_session::context(0).current_player;p.bytes_2c[2]=0;if(stone==8){stone=ps::read<int>(p,0x1c);p.bytes_2c[2]=1;}ps::write(p,0x14,stone);owner.unfocused_weapon=host.create_weapon(character,stone);owner.unfocused_weapon->role=1;owner.unfocused_weapon->stone_id=stone;}
void select_passive(WeaponStoneInf& owner,int character,int stone,Environment& host){host.destroy_weapon(owner.passive_weapon);owner.passive_weapon=nullptr;auto& p=*game_session::context(0).current_player;p.bytes_2c[3]=0;if(stone==8){stone=ps::read<int>(p,0x1c);p.bytes_2c[3]=1;}ps::write(p,0x18,stone);owner.passive_weapon=host.create_weapon(character,stone);owner.passive_weapon->role=3;owner.passive_weapon->stone_id=stone;}
void refresh_selection(WeaponStoneInf& owner,int character,Environment& host){auto& p=*game_session::context(0).current_player;select_main(owner,character,ps::read<int>(p,0x1c),host);select_unfocused(owner,character,ps::read<int>(p,0x24),host);select_focused(owner,character,ps::read<int>(p,0x20),host);select_passive(owner,character,ps::read<int>(p,0x28),host);}
void initialize_option(WeaponStoneInf& owner,player_entity::Option& option,int index){owner.focused_weapon->initialize_focused_option(&option,index);owner.unfocused_weapon->initialize_unfocused_option(&option,index);}
int script_variant(WeaponStoneInf& owner){auto& p=*static_cast<player_entity::Player*>(game_session::context(0).objects_04[0]);return p.focused_204c?owner.focused_weapon->script_variant():owner.unfocused_weapon->script_variant();}
const sprite::Vec2* option_offset(WeaponStoneInf& owner,int level,int index,bool focused){return focused?owner.focused_weapon->focused_offset(level,index):owner.unfocused_weapon->unfocused_offset(level,index);}
}
