from pathlib import Path
import hashlib,json,subprocess,sys
base=Path(__file__).resolve().parent;root=base.parents[1]
addresses=[0x511770,0x5117e0,0x511870,0x511900,0x511930,0x511980,0x5119e0,0x511a30,0x511af0,0x511cf0,0x511ed0,0x511f00,0x512090,0x5120d0,0x512980,0x512aa0,0x512f30,0x512f60,0x512fb0,0x513710,0x513cc0,0x513ce0,0x513dd0,0x513f70,0x514080,0x5141e0,0x514240,0x49be20,0x4aaac0,0x4aadb0,0x4e67e0]
subprocess.run([sys.executable,str(root/'tools/extract_function_evidence.py'),'--output',str(base/'evidence'),*[f'{a:08x}' for a in addresses]],check=True)
paths=list(base.glob('*.hpp'))+list(base.glob('*.cpp'))+[base/'CMakeLists.txt']+list((base/'oracle').glob('*.cpp'))+list((base/'oracle').glob('*.hpp'))+list((base/'oracle').glob('*.inc'))+[base/'oracle/CMakeLists.txt']
dependencies=['runtime_state/state.hpp','runtime_state/state.cpp','ecl_vm/math.hpp','ecl_vm/math.cpp','ecl_vm/vm.cpp','game_session/session.hpp','runtime_core/runtime_core.hpp','runtime_core/runtime_core.cpp','core_scheduler/scheduler.hpp','core_scheduler/scheduler.cpp','sprite_renderer/animation.hpp','effect_system/parameters.cpp','effect_system/effect.hpp','gameplay/enemy_spawn.hpp','gameplay/enemy_entity.hpp','gameplay/enemy_variables.hpp','gameplay/player_state.hpp','text_renderer/text.hpp','program_entry/program_entry.hpp']
paths += [base.parent/name for name in dependencies]+[root/'native_recovered/native_core.hpp',root/'tests/native_cpu_compare.cpp']
hashes={p.relative_to(root).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}
report_path=base/'cpu_validation.json';report=json.loads(report_path.read_text())
if report['failed']:raise SystemExit('Cannot register failing special_state comparison')
report['source_hashes']=hashes
report['scope']='63,488 constructor/byte and float interpolation/color assertions;36,864 full update and draw assertions;16,384 collection/player reward/cancellation call assertions. Original entry is never called.'
report['boundaries']=['Enemy spawn/lookup/position, effect spawn, audio-independent animation deletion/free, and text submission use recorded boundaries; production binds actual recovered modules','Update comparisons include all176+4 Controller bytes,8 full Entry objects,Player,28-byte RNG,return values where defined and ordered cross-module arguments; original and source use the same deterministic random seed','Original mutex uses its single-thread recursive-owner path; concurrency scheduling is not compared','512fb0 entry initialization, actual allocator release, production adapters and direct GPU rendering compile and follow original instruction evidence but are not included in this CPU oracle','Destructor advances the intrusive iterator before freeing its current allocation to avoid the original post-free observer access; release order is preserved','Invalid forced color4, corrupt ownership/indices, allocation failures, zero RNG modulus and whole-game replay equivalence are outside the tested defined domain']
report_path.write_text(json.dumps(report,indent=2)+'\n')
status={'status':'compiled_source_module_with_explicit_unrecovered_dependencies','full_game_equivalence':False,'original_va':[f'0x{a:08x}' for a in addresses],'source_hashes':hashes,'cpu_validation':'cpu_validation.json','unrecovered_game_symbols':['startup::unrecovered::owner_005c6114 (used only as real pointer gate)','HUD boss-collection query through existing item::Environment (0x00478160)'],'source_dependencies':['th20_runtime_state','th20_ecl_vm','th20_core_scheduler','th20_effect_system','th20_gameplay','th20_item_system','th20_bullet_system','th20_laser_system','th20_text_renderer'],'limitations':report['boundaries']}
(base/'module_status.json').write_text(json.dumps(status,indent=2)+'\n');print(f'{len(addresses)} evidence addresses; {report["passed"]} passed; {report["failed"]} failed')
