const std::pair<unsigned,void*> selection_hooks[]={{0x52ccd0,&signal_only},{0x52cd10,&signal_execute},{0x52c240,&child_lookup},{0x44ef90,&child_interrupt},{0x44f0d0,&child_execute},{0x450120,&hide_child},{0x44fa30,&show_child},{0x52c870,&extra_character},{0x52c4f0,&cleared_character},{0x52c640,&cleared_difficulty},{0x464100,&selected_profile},{0x50f660,&commit_progress},{0x534420,&main_weapon},{0x5347d0,&unfocused_weapon},{0x5344d0,&focused_weapon},{0x534600,&passive_weapon}};
for(auto [va,target]:selection_hooks)hook(va,target);
std::vector<unsigned char> renderer_storage(sizeof(th20::source::text::Renderer));at<void*>(0x5c0698)=renderer_storage.data();
SelectionHost selection_host(host);FloatingEnvironment::prepare();
for(unsigned page=0;page<2;++page)for(unsigned test=0;test<16384;++test){
 for(unsigned i=0;i<sizeof(object);++i)if(i<0x24||i>=0x70)storage[i]=std::uint8_t(random());
 auto& c=object.cursor;host.session.player_table.field_1e0=(test/5)%5;object.state=5+page;object.previous_state=random()%6;object.phase=test%5;
 c.count=page?2:host.session.player_table.field_1e0==4?1:4;c.current=random()%c.count;c.previous=random();c.minimum=0;c.wrapping=page?1:0;c.excluded.clear();c.history.first=c.secondary_history.first=0;c.history.size=c.secondary_history.size=1;history[0][0]=page?1:0;history[1][0]=page?4:10;
 object.handle390=test%3?4001:0;object.handles[12]=object.handles[14]=test%3?0:1;
 th20::recovered::timer_set(object.age,int((test/25)%22));th20::recovered::timer_set(object.selection_age,0);th20::recovered::timer_set(object.flash_age,0);
 at<unsigned>(0x5b88c0)=random()&0x801ff;at<unsigned>(0x5b88b8)=random()&0xf0;at<int>(0x5b0a60)=random()%4;at<int>(0x5c6140)=random()%2;at<int>(0x5c6144)=random()%9;at<unsigned>(0x5c6128)=(test/100)%7;host.session.mode=random()%3;host.session.contexts[0].current_player->fields_00[2]=random()%2;
 character_extra[0]=(test/50)%2;character_extra[1]=true;for(auto& row:complete)for(auto& value:row)value=random()%2;for(auto& row:profiles)for(auto& value:row)value=random()%9;
 const auto before_session=host.session;const auto before_d=host.last_difficulty,before_c=host.last_character,before_p=selection_host.last_profile;std::array<unsigned char,sizeof(object)> before;std::memcpy(before.data(),&object,sizeof(object));int h_before[2][4];std::memcpy(h_before,history,sizeof(history));int ex_before[16];std::memcpy(ex_before,c.excluded.data(),64);
 trace.clear();cpu<void>(page?0x521060:0x521bc0,&object);const auto expected_trace=trace;const auto expected_session=host.session;const auto ed=host.last_difficulty,ec=host.last_character,ep=selection_host.last_profile;std::array<unsigned char,sizeof(object)> expected;std::memcpy(expected.data(),&object,sizeof(object));int eh[2][4];std::memcpy(eh,history,sizeof(history));int ex[16];std::memcpy(ex,c.excluded.data(),64);
 host.session=before_session;host.last_difficulty=before_d;host.last_character=before_c;selection_host.last_profile=before_p;std::memcpy(&object,before.data(),sizeof(object));std::memcpy(history,h_before,sizeof(history));std::memcpy(c.excluded.data(),ex_before,64);trace.clear();if(page)ti::update_character(object,selection_host);else ti::update_difficulty(object,selection_host);
 check(page?"character_object":"difficulty_object",test,expected.data(),&object,sizeof(object));check("selection_session",test,&expected_session,&host.session,sizeof(host.session));check("selection_history",test,eh,history,sizeof(history));check("selection_excluded",test,ex,c.excluded.data(),64);check("last_difficulty",test,&ed,&host.last_difficulty,4);check("last_character",test,&ec,&host.last_character,4);check("last_profile",test,&ep,&selection_host.last_profile,4);const auto es=expected_trace.size(),as=trace.size();check("selection_trace_size",test,&es,&as,4);if(es==as)check("selection_trace",test,expected_trace.data(),trace.data(),es*4);
}
