#define wmain unused_native_cpu_main
#include "../../../tests/native_cpu_compare.cpp"
#undef wmain
#include "../completion.hpp"
#include "../replay_access.hpp"
#include "../../startup_scene/startup.hpp"
namespace th20::source::startup::unrecovered {runtime::CallbackOwner* owner_005c60fc=nullptr;}
#include "../../gameplay/player_state.hpp"
#include "../../progress_state/records.hpp"
namespace gp=th20::source::gameplay;namespace gs=th20::source::game_session;namespace ps=gp::player_state;namespace pr=th20::source::progress;
template<class R,class... A>R cpu(unsigned va,void* self,A... args){using F=R(__thiscall*)(void*,A...);return reinterpret_cast<F>(mapped_image_base+va-0x400000)(self,args...);}
alignas(gp::GameController) unsigned char game_storage[sizeof(gp::GameController)];auto& game=*reinterpret_cast<gp::GameController*>(game_storage);
gs::Session* session;pr::Profile profile;std::vector<unsigned> trace;int available[9];bool unlocked[64],replay_available;
void event(unsigned id,unsigned a=0){trace.insert(trace.end(),{id,a});}
struct Host final:gp::CompletionEnvironment {
 gp::GameController& game()override{return ::game;}gs::Session& session()override{return *::session;}pr::Profile& profile()override{return ::profile;}
 bool replay_has_stage(int stage)override{event(1,stage);return replay_available;}
 void finish_player()override{event(2);}void update_playtime()override{event(3);}void finish_practice()override{event(4);}void finish_replay()override{event(5);}
 void mark_hud_clear()override{event(6);}void achievement(int index)override{event(7,index);}int stone_count(unsigned index)override{event(8,index);return available[index];}void notify_unlock(unsigned index)override{event(9,index);}void grant_stone(unsigned index)override{event(10,index);}bool unlock_flag(unsigned index)override{event(11,index);return unlocked[index];}
 int& replay_selection()override{return *reinterpret_cast<int*>(mapped_image_base+0x1afcfc);}void select_scene(int scene,bool guarded)override{event(12,scene);event(13,guarded);}void advance_stage()override{event(14);auto& table=::session->player_table;int value=ps::read<int>(table,0x1f4);if(value<7)++value;ps::write(table,0x1f4,value);}
} host;
int __fastcall replay_boundary(void*,void*,int stage){return host.replay_has_stage(stage);}void* __cdecl player_boundary(int){return reinterpret_cast<void*>(1);}
void __fastcall player_finish(void*,void*){host.finish_player();}void __fastcall playtime(void*,void*){host.update_playtime();}void __fastcall practice(void*,void*){host.finish_practice();}void __fastcall replay_end(void*,void*){host.finish_replay();}
void __fastcall hud_clear(void*,void*){host.mark_hud_clear();}void* __cdecl award(int index){host.achievement(index);return nullptr;}
int __fastcall stone_count(void*,void*,unsigned index){return host.stone_count(index);}void __fastcall unlock_notify(void*,void*,unsigned index){host.notify_unlock(index);}void __fastcall stone_grant(void*,void*,unsigned index){host.grant_stone(index);}int __fastcall unlock_query(void*,void*,unsigned index){return host.unlock_flag(index);}
void __fastcall scene_guarded(void*,void*,int value){host.select_scene(value,true);}void __fastcall scene_plain(void*,void*,int value){host.select_scene(value,false);}void __fastcall advance(void*,void*){host.advance_stage();}
pr::Profile* __fastcall profile_get(void*,void*){return &profile;}
int wmain(int argc,wchar_t** argv){try{
 if(argc!=3)throw std::runtime_error("Usage: stage_compare ORIGINAL.exe REPORT.json");const auto bytes=th20::read_file(argv[1]);if(sha256(bytes)!=expected_sha)throw std::runtime_error("Original SHA mismatch");const auto info=th20::parse_pe(bytes);Mapping image(bytes,info);mapped_image_base=image.address();session=reinterpret_cast<gs::Session*>(mapped_image_base+0x1ba568);
 std::array<unsigned char,5> original_recorded_getter;std::memcpy(original_recorded_getter.data(),reinterpret_cast<void*>(mapped_image_base+0x88770),5);
 auto hook=[&](unsigned va,void* target){auto* p=reinterpret_cast<unsigned char*>(mapped_image_base+va-0x400000);p[0]=0xe9;*reinterpret_cast<unsigned*>(p+1)=reinterpret_cast<unsigned>(target)-reinterpret_cast<unsigned>(p+5);FlushInstructionCache(GetCurrentProcess(),p,5);};
 hook(0x488770,reinterpret_cast<void*>(&replay_boundary));hook(0x460830,reinterpret_cast<void*>(&player_boundary));hook(0x4bd0c0,reinterpret_cast<void*>(&player_finish));hook(0x4bce10,reinterpret_cast<void*>(&playtime));hook(0x4e59e0,reinterpret_cast<void*>(&practice));hook(0x4e5f30,reinterpret_cast<void*>(&replay_end));hook(0x4bdbd0,reinterpret_cast<void*>(&hud_clear));hook(0x52f900,reinterpret_cast<void*>(&award));hook(0x4bd610,reinterpret_cast<void*>(&stone_count));hook(0x4bddc0,reinterpret_cast<void*>(&unlock_notify));hook(0x4bcf60,reinterpret_cast<void*>(&stone_grant));hook(0x4bd780,reinterpret_cast<void*>(&unlock_query));hook(0x4a0fb0,reinterpret_cast<void*>(&scene_guarded));hook(0x4be250,reinterpret_cast<void*>(&scene_plain));hook(0x4bd8a0,reinterpret_cast<void*>(&advance));hook(0x50fc50,reinterpret_cast<void*>(&profile_get));*reinterpret_cast<void**>(mapped_image_base+0x1ba828)=&game;
 std::mt19937 random(0x4bc570);unsigned passed=0,failed=0;std::vector<std::string> failures;
 auto fill=[&](auto& p){auto* at=reinterpret_cast<unsigned char*>(&p);for(unsigned i=0;i<sizeof(p);++i)at[i]=std::uint8_t(random());};
 auto check=[&](const char* label,unsigned test,const void* e,const void* a,std::size_t size){if(!std::memcmp(e,a,size)){++passed;return;}++failed;if(failures.size()<30){std::ostringstream out;out<<label<<" test="<<test;for(std::size_t i=0;i<size;++i)if(static_cast<const unsigned char*>(e)[i]!=static_cast<const unsigned char*>(a)[i]){out<<" offset="<<std::hex<<i<<" expected="<<unsigned(static_cast<const unsigned char*>(e)[i])<<" actual="<<unsigned(static_cast<const unsigned char*>(a)[i]);break;}failures.push_back(out.str());}};
 for(unsigned test=0;test<16384;++test){
  fill(game_storage);fill(*session);fill(profile);session->contexts[0].current_player=&session->player_table.players[test%2];game.restart_mode=int(test%3);session->mode=int((test/3)%4);ps::write(session->player_table,0x1f4,int((test/12)%11)-2);session->player_table.field_1e0=(test/132)%5;session->player_table.continue_count=int(random()%15)-3;ps::write(session->player_table,0x208,int(random()%4)-1);ps::write(session->player_table,0x204,int(random()%120)-4);ps::write(*session->contexts[0].current_player,8,int(test%2));ps::write(*session->contexts[0].current_player,12,int((test/2)%8));
  for(int index=0;index<5;++index){const int edge[]{-1,0,99998,99999,100000};pr::write(profile.bytes,0x76b8+index*4,edge[random()%5]);pr::write(profile.bytes,0x76d4+index*4,edge[random()%5]);}for(auto& value:available)value=int(random()%14)-2;for(auto& flag:unlocked)flag=random()%2;replay_available=test%2;host.replay_selection()=int(test%3)-1;
  std::array<unsigned char,sizeof(game)> game_before;std::memcpy(game_before.data(),&game,sizeof(game));std::array<unsigned char,sizeof(gs::Session)> session_before;std::memcpy(session_before.data(),session,sizeof(*session));const auto profile_before=profile;const auto selection_before=host.replay_selection();trace.clear();const int er=cpu<int>(0x4bc570,&game);std::array<unsigned char,sizeof(game)> expected_game;std::memcpy(expected_game.data(),&game,sizeof(game));std::array<unsigned char,sizeof(gs::Session)> expected_session;std::memcpy(expected_session.data(),session,sizeof(*session));const auto expected_profile=profile;const auto expected_trace=trace;const auto expected_selection=host.replay_selection();
  std::memcpy(&game,game_before.data(),sizeof(game));std::memcpy(session,session_before.data(),sizeof(*session));profile=profile_before;host.replay_selection()=selection_before;trace.clear();const int ar=gp::complete_stage(game,host);check("stage_return",test,&er,&ar,4);check("stage_game",test,expected_game.data(),&game,sizeof(game));check("stage_session",test,expected_session.data(),session,sizeof(*session));check("stage_profile",test,&expected_profile,&profile,sizeof(profile));check("stage_replay_selection",test,&expected_selection,&host.replay_selection(),4);const auto ec=expected_trace.size(),ac=trace.size();check("stage_trace_size",test,&ec,&ac,4);if(ec==ac)check("stage_trace",test,expected_trace.data(),trace.data(),ec*4);
 }
 std::memcpy(reinterpret_cast<void*>(mapped_image_base+0x88770),original_recorded_getter.data(),5);FlushInstructionCache(GetCurrentProcess(),reinterpret_cast<void*>(mapped_image_base+0x88770),5);
 alignas(8) unsigned char replay_owner[0x300];th20::source::startup::unrecovered::owner_005c60fc=reinterpret_cast<th20::source::runtime::CallbackOwner*>(replay_owner);
 for(unsigned test=0;test<4096;++test){fill(replay_owner);pr::write(replay_owner,0x10,int(test%5)-1);const int index=int(test%8);const bool expected_mode=cpu<bool>(0x488800,replay_owner),actual_mode=th20::source::replay::is_playback();check("replay_mode",test,&expected_mode,&actual_mode,1);void* expected_recording=cpu<void*>(0x488740,replay_owner,index);void* actual_recording=th20::source::replay::recording_stage(index);check("replay_recording",test,&expected_recording,&actual_recording,4);const void* expected_recorded=cpu<void*>(0x488770,replay_owner,index);const void* actual_recorded=th20::source::replay::recorded_stage(index);check("replay_recorded",test,&expected_recorded,&actual_recorded,4);}
 std::ofstream out(argv[2]);out<<"{\"original_sha256\":"<<th20::json_string(expected_sha)<<",\"passed\":"<<passed<<",\"failed\":"<<failed<<",\"failures\":[";for(unsigned i=0;i<failures.size();++i){if(i)out<<",";out<<th20::json_string(failures[i]);std::cerr<<failures[i]<<"\n";}out<<"]}\n";std::cout<<"passed="<<passed<<" failed="<<failed<<"\n";return failed?1:0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 2;}}
