// Isolated observation executable. It runs the complete original5240d0, never
// patches instructions, and reports the exact reference-resource input.
#define wmain unused_native_cpu_main
#include "../../tests/native_cpu_compare.cpp"
#undef wmain
#include "title.hpp"
#include "../replay_system/replay.hpp"
#include "../archive/archive.hpp"
#include <ctime>
#include <memory>
namespace rp=th20::source::replay;namespace ti=th20::source::title;namespace tx=th20::source::text;
template<class R,class...A>R probe_cpu(unsigned va,void* self,A...args){using F=R(__thiscall*)(void*,A...);return reinterpret_cast<F>(mapped_image_base+va-0x400000)(self,args...);}
int wmain(int argc,wchar_t**argv){try{
    if(argc!=5&&argc!=6)throw std::runtime_error("Usage: replay_format_probe ORIGINAL.exe ACTUAL.rpy PAGE OUTPUT.txt [SLOWDOWN_FLOAT]");
    std::ofstream output(argv[4]);static std::ofstream* event_output=nullptr;event_output=&output;
    SetErrorMode(SEM_FAILCRITICALERRORS|SEM_NOGPFAULTERRORBOX);
    AddVectoredExceptionHandler(1,[](PEXCEPTION_POINTERS p)->LONG{if(p->ExceptionRecord->ExceptionCode==EXCEPTION_ACCESS_VIOLATION){*event_output<<"native_access_violation original_va="<<std::hex<<(p->ContextRecord->Eip-mapped_image_base+0x400000)<<" address="<<p->ExceptionRecord->ExceptionInformation[1]<<" eip="<<p->ContextRecord->Eip<<"\n"<<std::flush;std::cerr<<"native access violation at "<<std::hex<<(p->ContextRecord->Eip-mapped_image_base+0x400000)<<" address "<<p->ExceptionRecord->ExceptionInformation[1]<<std::endl;}return EXCEPTION_CONTINUE_SEARCH;});
    const auto image_bytes=th20::read_file(argv[1]);if(sha256(image_bytes)!=expected_sha)throw std::runtime_error("Original SHA mismatch");const auto info=th20::parse_pe(image_bytes);Mapping image(image_bytes,info);mapped_image_base=image.address();
    for(const auto& item:info.imports){for(const auto* name:{L"kernel32.dll",L"gdi32.dll",L"user32.dll"})if(auto dll=GetModuleHandleW(name))if(auto entry=GetProcAddress(dll,item.name.c_str())){*reinterpret_cast<FARPROC*>(mapped_image_base+item.iat_rva)=entry;break;}}
    *reinterpret_cast<HANDLE*>(mapped_image_base+0x1e5990)=GetProcessHeap();auto* lock=reinterpret_cast<unsigned*>(mapped_image_base+0x1c0240+18*0x30);std::memset(lock,0,0x30);lock[0]=0x101;lock[10]=GetCurrentThreadId();lock[11]=1;
    _tzset();long timezone=0,bias=0;int daylight=0;_get_timezone(&timezone);_get_dstbias(&bias);_get_daylight(&daylight);if(daylight)throw std::runtime_error("Probe requires non-DST host timezone");*reinterpret_cast<long*>(mapped_image_base+0x1e5898)=timezone;*reinterpret_cast<int*>(mapped_image_base+0x1e589c)=0;*reinterpret_cast<long*>(mapped_image_base+0x1e58a0)=bias;*reinterpret_cast<unsigned*>(mapped_image_base+0x1e58b4)=1;
    auto raw=th20::read_file(argv[2]);const auto* header=reinterpret_cast<const rp::FileHeader*>(raw.data());if(raw.size()<0x30||header->magic!=0x72303274u||header->packed_size>raw.size()-0x30)throw std::runtime_error("Invalid replay resource");th20::source::Bytes packed(raw.begin()+0x30,raw.begin()+0x30+header->packed_size);th20::source::decrypt(packed,{0x5c,0xe1,0x400,header->packed_size});th20::source::decrypt(packed,{0x7d,0x3a,0x100,header->packed_size});th20::source::LzssDecoder decoder;auto decoded=decoder.decode(packed,header->unpacked_size);if(decoded.size()<0x100)throw std::runtime_error("Truncated replay resource");
    auto title_memory=std::make_unique<std::uint8_t[]>(sizeof(ti::TitleInf)),renderer_memory=std::make_unique<std::uint8_t[]>(sizeof(tx::Renderer)),replay_memory=std::make_unique<std::uint8_t[]>(sizeof(rp::ReplayInf));auto& title=*reinterpret_cast<ti::TitleInf*>(title_memory.get());auto& renderer=*reinterpret_cast<tx::Renderer*>(renderer_memory.get());auto& replay=*reinterpret_cast<rp::ReplayInf*>(replay_memory.get());replay.user=reinterpret_cast<rp::UserHeader*>(decoded.data());replay.header=const_cast<rp::FileHeader*>(header);replay.decoded=decoded.data();strcpy_s(replay.filename,"th20_ud0001.rpy");std::size_t offset=0x100;const unsigned count=replay.user->fields_d0[1]<8?replay.user->fields_d0[1]:6;for(unsigned i=0;i<count;++i){if(offset+sizeof(rp::StageRecord)>decoded.size())throw std::runtime_error("Invalid stage resource");auto* stage=reinterpret_cast<rp::StageRecord*>(decoded.data()+offset);if(stage->stage<0||stage->stage>=8)throw std::runtime_error("Stage index");replay.playback[stage->stage].stage=stage;offset+=sizeof(*stage)+stage->data_bytes;}
    if(argc==6){const float value=static_cast<float>(_wtof(argv[5]));std::memcpy(replay.user->fields_d0,&value,4);}
    const int page=_wtoi(argv[3]);if(page<0||page>3)throw std::runtime_error("Invalid page");title.phase=2;title.cursor108.current=page;title.cursor.current=0;title.metadata[page*25]=&replay;renderer.scale_x=renderer.scale_y=1;renderer.font_width=9;renderer.color=renderer.field_1a1c8=0xffffffff;renderer.shadow_color=0xff000000;*reinterpret_cast<void**>(mapped_image_base+0x1c0698)=&renderer;*reinterpret_cast<float*>(mapped_image_base+0x1b8818)=1;
    output<<"original_sha256="<<expected_sha<<"\nresource_sha256="<<sha256(raw)<<"\ndecoded_sha256="<<sha256(decoded)<<"\npage="<<page<<"\ntimestamp="<<replay.user->timestamp<<"\ncharacter="<<replay.user->fields_d0[2]<<"\nstone="<<replay.user->stones[0]<<"\ndifficulty="<<replay.user->difficulty<<"\nfinished_stage="<<replay.user->finished_stage<<"\nslowdown_bits="<<std::hex<<replay.user->fields_d0[0]<<"\nformat="<<reinterpret_cast<const char*>(*reinterpret_cast<unsigned*>(mapped_image_base+0x1b0a74+(page?2:0)*4))<<"\n"<<std::flush;
    FloatingEnvironment::prepare();const int result=probe_cpu<int>(0x5240d0,&title);output<<"returned="<<result<<" lines="<<renderer.line_count<<"\n";for(int i=0;i<renderer.line_count;++i)output<<renderer.lines[i].text<<"\n";std::cout<<"original returned "<<result<<" lines="<<renderer.line_count<<"\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 2;}}
