from pathlib import Path
import hashlib,json,subprocess,sys
base=Path(__file__).resolve().parent;root=base.parents[1]
addresses=[0x4aee90,0x4aef00,0x4afa70,0x4bed50,0x4bfa00,0x515b50,0x515b90,0x516170,0x5163c0,0x5167b0,0x5189c0,0x519840,0x5198d0,0x519960,0x51a0b0,0x51b6d0,0x51c6f0,0x51c7a0,0x51c8b0,0x51cc20,0x438f10,0x44c670,0x44c6b0,0x44efc0]
subprocess.run([sys.executable,str(root/'tools/extract_function_evidence.py'),'--output',str(base/'evidence'),*[f'{a:08x}' for a in addresses]],check=True)
paths=list(base.glob('*.hpp'))+list(base.glob('*.cpp'))+[base/'names.inc',base/'CMakeLists.txt']+list((base/'oracle').glob('*.cpp'))+list((base/'oracle').glob('*.hpp'))+list((base/'oracle').glob('*.inc'))+[base/'oracle/CMakeLists.txt']
dependencies=['runtime_state/state.hpp','runtime_state/state.cpp','game_session/session.hpp','game_session/session.cpp','runtime_core/callback_owner.hpp','runtime_core/runtime_core.cpp','core_scheduler/scheduler.hpp','core_scheduler/scheduler.cpp','sprite_renderer/animation.hpp','sprite_renderer/sprite.hpp','sprite_renderer/menu_animation.hpp','sprite_renderer/menu_animation.cpp','sprite_renderer/loading_interrupt.cpp','effect_system/parameters.cpp','effect_system/effect.hpp','program_entry/program_entry.hpp','input/input.hpp']
paths += [base.parent/name for name in dependencies]+[root/'native_recovered/native_core.hpp',root/'tests/native_cpu_compare.cpp',root/'assets/raw/stonetext.txt']
hashes={p.relative_to(root).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}
report_path=base/'cpu_validation.json';report=json.loads(report_path.read_text())
if report['failed']:raise SystemExit('Cannot register failing StoneMenu comparison')
report['source_hashes']=hashes
report['scope']='39,856 cursor, complete owner construction, initialization, text parsing and lifecycle assertions;16,000 draw assertions;9,216 sprite crop, recursive child and immediate interrupt assertions;45,056 complete update/open assertions. Original game entry is never called.'
report['boundaries']=['Resource, scheduler callback insertion, animation spawning/VM execution, audio, metadata mutation, overlay and special-color queries use recorded external boundaries in the oracle; production binds recovered modules or explicit unrecovered interfaces','Full owner, all test animation objects, Player state, used counts, selected slots, text state, return values and ordered boundary arguments are compared','Original text parser runs against the stock stonetext.txt with compatible host stringstream construction/getline/destruction boundaries','Tests exercise valid finite gameplay states and empty cursor history ownership; corrupt ownership, invalid indexes, all-excluded cursor loops, allocation failure, NaN gameplay coordinates, full GPU output and integrated replay equivalence are outside this oracle']
report_path.write_text(json.dumps(report,indent=2)+'\n')
status={'status':'compiled_source_module_with_explicit_unrecovered_dependencies','full_game_equivalence':False,'original_va':[f'0x{a:08x}' for a in addresses],'source_hashes':hashes,'cpu_validation':'cpu_validation.json','unrecovered_game_symbols':['stone_menu::unrecovered::refresh_overlay_selection (0x00534080)'],'source_dependencies':['th20_runtime_state','th20_game_session','th20_core_scheduler','th20_sprite_renderer','th20_progress_state','th20_effect_system','th20_resource_manager','th20_text_renderer','th20_input','th20_audio_runtime'],'limitations':report['boundaries']}
(base/'module_status.json').write_text(json.dumps(status,indent=2)+'\n');print(f'{len(addresses)} evidence addresses; {report["passed"]} passed; {report["failed"]} failed')
